USE [master]
GO
/****** Object:  Database [CarritoBD]    Script Date: 16/06/2021 16:42:34 ******/
CREATE DATABASE [CarritoBD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CarritoBD', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CarritoBD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CarritoBD_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CarritoBD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CarritoBD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CarritoBD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CarritoBD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CarritoBD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CarritoBD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CarritoBD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CarritoBD] SET ARITHABORT OFF 
GO
ALTER DATABASE [CarritoBD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CarritoBD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CarritoBD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CarritoBD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CarritoBD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CarritoBD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CarritoBD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CarritoBD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CarritoBD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CarritoBD] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CarritoBD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CarritoBD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CarritoBD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CarritoBD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CarritoBD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CarritoBD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CarritoBD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CarritoBD] SET RECOVERY FULL 
GO
ALTER DATABASE [CarritoBD] SET  MULTI_USER 
GO
ALTER DATABASE [CarritoBD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CarritoBD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CarritoBD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CarritoBD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CarritoBD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CarritoBD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CarritoBD', N'ON'
GO
ALTER DATABASE [CarritoBD] SET QUERY_STORE = OFF
GO
USE [CarritoBD]
GO
/****** Object:  Table [dbo].[Categoria]    Script Date: 16/06/2021 16:42:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Categoria](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ListaVenta]    Script Date: 16/06/2021 16:42:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListaVenta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[VentaId] [int] NULL,
	[ProductoId] [int] NULL,
	[Cantidad] [int] NULL,
	[Total] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Producto]    Script Date: 16/06/2021 16:42:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Producto](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NULL,
	[Precio] [float] NULL,
	[FechaCreacion] [datetime] NULL,
	[Foto] [varchar](200) NULL,
	[CategoriaId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Venta]    Script Date: 16/06/2021 16:42:35 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Venta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiaVenta] [datetime] NULL,
	[Subtotal] [float] NULL,
	[Iva] [float] NULL,
	[Total] [float] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ListaVenta]  WITH CHECK ADD FOREIGN KEY([ProductoId])
REFERENCES [dbo].[Producto] ([Id])
GO
ALTER TABLE [dbo].[ListaVenta]  WITH CHECK ADD FOREIGN KEY([VentaId])
REFERENCES [dbo].[Venta] ([Id])
GO
ALTER TABLE [dbo].[Producto]  WITH CHECK ADD FOREIGN KEY([CategoriaId])
REFERENCES [dbo].[Categoria] ([Id])
GO
USE [master]
GO
ALTER DATABASE [CarritoBD] SET  READ_WRITE 
GO
